<?php

namespace JD\JolydaysBundle\Repository;

/**
 * IllustrationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IllustrationsRepository extends \Doctrine\ORM\EntityRepository
{
}
