<?php

namespace JD\JolydaysBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPostByCategory(array $categories)
  {
    $qb = $this->createQueryBuilder('a');

    // join entity posts with category c and filter by category names
    $qb
      ->innerJoin('a.categories', 'c')
      ->addSelect('c');

    $qb->where($qb->expr()->in('c.name', $categories));
    return $qb->getQuery()->getResult();
  }
}
