<?php

namespace JD\JolydaysBundle\Repository;

/**
 * SingleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SingleRepository extends \Doctrine\ORM\EntityRepository
{
}
