# Homepage with pagination
jd_jolydays_homepage:
  path: /{page}
  defaults:
    _controller: JDJolydaysBundle:Posts:index
    page: 1
  requirements: 
    page: \d*

# To view single post
jd_jolydays_view:
  path: /post/{post_id}
  defaults:
    _controller: JDJolydaysBundle:Posts:view
  requirements: 
    post_id: \d+

jd_jolydays_add:
  path: /add
  defaults:
    _controller: JDJolydaysBundle:Posts:add

# To edit post with post_id id
jd_jolydays_edit:
  path: /edit/{post_id}
  defaults:
    _controller: JDJolydaysBundle:Posts:edit
  requirements:
    post_id: \d+

# To delete the post with post_id id
jd_jolydays_delete:
  path: /delete/{post_id}
  defaults:
    _controller: JDJolydaysBundle:Posts:delete
  requirements:
    post_id: \d+

# a page to show all posts of a category
jd_jolydays_posts_in_cat:
  path: /category/{cat_name}
  defaults:
    _controller: JDJolydaysBundle:Posts:postsInCat

jd_jolydays_result:
  path: /result
  defaults:
    _controller: JDJolydaysBundle:Posts:search
